kube-prometheus-stack:
  grafana:
    assertNoLeakedSecrets: false

    adminUser: admin
    adminPassword: grafana101

    deploymentStrategy:
      type: RollingUpdate

    sidecar:
      enabled: true
      defaultDatasourceEnabled: true

      resources:
        limits:
          memory: 200Mi
        requests:
          cpu: 5m
          memory: 64Mi

      alerts:
        enabled: true
        label: grafana_alert
        labelValue: "1"
        searchNamespace: ALL

      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL

    grafana.ini:
      users:
        auto_assign_org: true
        auto_assign_org_role: Admin

      auth.basic:
        enabled: true
        password_policy: false

      feature_toggles:
        alertingSimplifiedRouting: true
        alertingQueryAndExpressionsStepMode: true
        displayAnonymousStats: true

  prometheus:
    enabled: true
    prometheusSpec:
      scrapeInterval: 15s
      evaluationInterval: 15s
      # Habilita scrape de targets adicionais
      additionalScrapeConfigs: |
        - job_name: "grafana"
          static_configs:
            - targets: ["app-grafana.default:80"]

  loki:
    enabled: false

  promtail:
    enabled: false

  alertmanager:
    enabled: false
